### ISSUE TITLE
Doesn't print welcome message if you run the bot and then add it to the server

### ISSUE THREAD

**Issue by PaperBag42** [PaperBag42/cheat.sh-discord#7]
**Describe the bug**
Don't tell me what to do

**To Reproduce**
1. Run the bot
2. Generate link
3. Click the link to add the bot to a server
4. It doesn't print the message

**Expected behavior**
It should print the message

**Screenshots**
Svartzun I think you went a little too far with this template thing

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version idk

**Smartphone (please complete the following information):**
The fuck this isn't even related

**Additional context**
Was this auto-generated or did you write all of this?

**Comment by YotamShvartsun** [comment]
That's the default, I just clicked OK:smile:
